### ISSUE TITLE
Can't install Hue.

### ISSUE THREAD

**Issue by niccolomondino** [steven-dfheinz/dfhz_hdp_mpack#2]
I have a problem when I try to install Hue from the ambari 'add service' functionality.
It fails immediately throwing an error on **Hue Server Install**.

Here is the error log:

**StErr:
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 38, in <module>
    BeforeAnyHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 31, in hook
    setup_users()
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 50, in setup_users
    groups = params.user_to_groups_dict[user],
KeyError: u'hue'
Error: Error: Unable to run the custom hook script ['/usr/bin/python', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-816.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-816.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']**

**stdout:   /var/lib/ambari-agent/data/output-816.txt
2021-04-14 15:36:48,045 - Stack Feature Version Info: Cluster Stack=3.1, Command Stack=None, Command Version=None -> 3.1
2021-04-14 15:36:48,052 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2021-04-14 15:36:48,054 - Group['livy'] {}
2021-04-14 15:36:48,055 - Group['spark'] {}
2021-04-14 15:36:48,056 - Group['ranger'] {}
2021-04-14 15:36:48,056 - Group['hdfs'] {}
2021-04-14 15:36:48,056 - Group['hue'] {}
2021-04-14 15:36:48,056 - Group['zeppelin'] {}
2021-04-14 15:36:48,057 - Group['hadoop'] {}
2021-04-14 15:36:48,057 - Group['users'] {}
2021-04-14 15:36:48,057 - User['yarn-ats'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,059 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,060 - User['infra-solr'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,061 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,062 - User['oozie'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2021-04-14 15:36:48,063 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,064 - User['ranger'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['ranger', 'hadoop'], 'uid': None}
2021-04-14 15:36:48,065 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2021-04-14 15:36:48,066 - User['zeppelin'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['zeppelin', 'hadoop'], 'uid': None}
2021-04-14 15:36:48,067 - User['accumulo'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2021-04-14 15:36:48,068 - User['livy'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['livy', 'hadoop'], 'uid': None}
2021-04-14 15:36:48,070 - User['spark'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['spark', 'hadoop'], 'uid': None}
2021-04-14 15:36:48,071 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2021-04-14 15:36:48,072 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop'], 'uid': None}
Error: Error: Unable to run the custom hook script ['/usr/bin/python', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-816.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-816.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']
2021-04-14 15:36:48,098 - The repository with version 3.1.4.0-315 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2021-04-14 15:36:48,103 - Skipping stack-select on HUE because it does not exist in the stack-select package structure.
Command failed after 1 tries**

Can anybody help me?

**Comment by steven-matison** [comment]
There is a step for a workaround in my hue repo documentation.  You must execute that command to disable user:group management.

**Comment by niccolomondino** [comment]
Thank you for the answer! Sorry for this question but where is your hue repo documentation?

**Comment by niccolomondino** [comment]
Thank you for the answer! I'll try it.
